In [ ]:
import psycopg2 as psy

# Connection
connection  = psy.connect( user = "postgres", password = "password", host= "localhost", port="5432")
cur = connection.cursor()
        
user = """
        CREATE TABLE Userr (
             id SERIAL PRIMARY KEY,
             lastName VARCHAR(255) NOT NULL,
             firstName VARCHAR(255) NOT NULL
        )
        """

groupg = """
         CREATE TABLE Groupg(
         id SERIAL PRIMARY KEY,
         name VARCHAR(255)
         )"""

belongs = """
          CREATE TABLE belongs(
          groupId INTEGER NOT NULL,
          userId INTEGER NOT NULL,
          FOREIGN KEY (groupId)
                   REFERENCES Groupg(id)
                   ON UPDATE CASCADE ON DELETE CASCADE,
          FOREIGN KEY (userId)
                   REFERENCES Userr(id)
                   ON UPDATE CASCADE ON DELETE CASCADE,
          PRIMARY KEY (groupId, userId)
          )"""
          
privilege = """
            CREATE TABLE Privilege (
                 URI VARCHAR(2083) PRIMARY KEY,
                 Level INTEGER)"""

hasprivilege = """
               CREATE TABLE hasPrivilege (
                    userId INTEGER NOT NULL,
                    privilegeURI VARCHAR(2083) NOT NULL,
                    FOREIGN KEY (userId)
                            REFERENCES Userr(id)
                            ON UPDATE CASCADE ON DELETE CASCADE,
                    FOREIGN KEY (privilegeURI)
                            REFERENCES Privilege(URI)
                            ON UPDATE CASCADE ON DELETE CASCADE,
                    PRIMARY KEY (userId, privilegeURI)
                    )"""

hasprivilege2 = """
               CREATE TABLE hasPrivilege2 (
                    groupId INTEGER NOT NULL,
                    privilegeURI VARCHAR(2083) NOT NULL,
                    FOREIGN KEY (groupId)
                            REFERENCES Groupg(id)
                            ON UPDATE CASCADE ON DELETE CASCADE,
                    FOREIGN KEY (privilegeURI)
                            REFERENCES Privilege(URI)
                            ON UPDATE CASCADE ON DELETE CASCADE,
                    PRIMARY KEY (groupId, privilegeURI)
                    )"""

access = """
         CREATE TABLE Access (
              userId INTEGER NOT NULL,
              AccessTime Date NOT NULL,
              ressource VARCHAR(2083) NOT NULL,
              comment VARCHAR(255),
              FOREIGN KEY (userId)
                      REFERENCES Userr (id)
                      ON UPDATE CASCADE ON DELETE CASCADE,
              PRIMARY KEY (userId, AccessTime, ressource, comment)
              )"""

tag = """
      CREATE TABLE Tag (
           id SERIAL PRIMARY KEY,
           name VARCHAR(255) NOT NULL
           )"""

source = """
         CREATE TABLE Source (
         URI VARCHAR(2083) PRIMARY KEY,
         description VARCHAR(255),
         userId INTEGER NOT NULL,
         FOREIGN KEY (userId)
                 REFERENCES Userr (id)
                 ON UPDATE CASCADE ON DELETE CASCADE)"""

sourcefrom = """
             CREATE TABLE sourceFrom (
                  sourceURI VARCHAR(2083) NOT NULL,
                  sourceFromURI VARCHAR(2083) NOT NULL,
                  FOREIGN KEY (sourceURI)
                          REFERENCES Source (URI)
                          ON UPDATE CASCADE ON DELETE CASCADE,
                  FOREIGN KEY (sourceFromURI)
                          REFERENCES Source (URI)
                          ON UPDATE CASCADE ON DELETE CASCADE,
                  PRIMARY KEY (sourceURI, sourceFromURI))"""

correspond = """
             CREATE TABLE correspond (
                  sourceURI VARCHAR(2083) NOT NULL,
                  tagId INTEGER NOT NULL,
                  FOREIGN KEY (sourceURI)
                          REFERENCES Source (URI)
                          ON UPDATE CASCADE ON DELETE CASCADE,
                  FOREIGN KEY (tagId)
                          REFERENCES Tag (id)
                          ON UPDATE CASCADE ON DELETE CASCADE,
                  PRIMARY KEY (sourceURI, tagId))"""

ingest = """
         CREATE TABLE Ingest (
              id SERIAL PRIMARY KEY,
              ingestionMode VARCHAR(255),
              ingestionStartTime VARCHAR(255) NOT NULL,
              definedDuration INTEGER NOT NULL,
              ingestionEndTime VARCHAR(255) NOT NULL,
              ingestionMethodNmae VARCHAR(255),
              ingestionSourceCodeUrl VARCHAR(2083),
              ingestionBinaryMachineCodeUrl VARCHAR(2083),
              ingestionEnvironement VARCHAR(255),
              ingestionResult VARCHAR(255),
              ingestionOutputLog VARCHAR(255),
              ingestionErrorLog VARCHAR(255),
              ingestionComment VARCHAR(255),
              userId INTEGER NOT NULL,
              FOREIGN KEY (userId)
                      REFERENCES Userr(id)
                      ON UPDATE CASCADE ON DELETE CASCADE)"""

sample = """
         CREATE TABLE Sample (
              URI VARCHAR(2083) PRIMARY KEY,
              name VARCHAR(255) NOT NULL,
              type VARCHAR(255) NOT NULL,
              creationDate Date NOT NULL,
              ingestId INTEGER NOT NULL,
              sourceURI VARCHAR(2083) NOT NULL,
              userId INTEGER NOT NULL,
              FOREIGN KEY (ingestId)
                      REFERENCES Ingest(id)
                      ON UPDATE CASCADE ON DELETE CASCADE,
              FOREIGN KEY (sourceURI)
                      REFERENCES Source(URI)
                      ON UPDATE CASCADE ON DELETE CASCADE,
              FOREIGN KEY (userId)
                      REFERENCES Userr(id)
                      ON UPDATE CASCADE ON DELETE CASCADE)"""

usermetadataString = """
                     CREATE TABLE User_metadata_string (
                          key VARCHAR(255) PRIMARY KEY,
                          valuev VARCHAR(255) NOT NULL,
                          sampleURI VARCHAR(2083) NOT NULL,
                          FOREIGN KEY (sampleURI)
                                  REFERENCES Sample(URI)
                                  ON UPDATE CASCADE ON DELETE CASCADE)"""

usermetadataInteger = """
                     CREATE TABLE User_metadata_integer (
                          key VARCHAR(255) PRIMARY KEY,
                          valuev INTEGER NOT NULL,
                          sampleURI VARCHAR(2083) NOT NULL,
                          FOREIGN KEY (sampleURI)
                                  REFERENCES Sample(URI)
                                  ON UPDATE CASCADE ON DELETE CASCADE)"""

dataset = """
          CREATE TABLE Dataset (
               id SERIAL PRIMARY KEY,
               name VARCHAR(255) NOT NULL,
               type VARCHAR(255),
               location VARCHAR(255),
               creationDate Date NOT NULL,
               userId INTEGER NOT NULL,
               FOREIGN KEY (userId)
                       REFERENCES Userr (id)
                       ON UPDATE CASCADE ON DELETE CASCADE)"""

includ = """
         CREATE TABLE Inclue (
              sampleURI VARCHAR(2083) NOT NULL,
              DatasetId INTEGER NOT NULL,
              FOREIGN KEY (sampleURI)
                      REFERENCES Sample(URI)
                      ON UPDATE CASCADE ON DELETE CASCADE,
              FOREIGN KEY (DatasetId)
                      REFERENCES Dataset(id)
                      ON UPDATE CASCADE ON DELETE CASCADE,
              PRIMARY KEY (sampleURI, DatasetId))"""

license = """
          CREATE TABLE License (
               URI VARCHAR(2083) PRIMARY KEY,
               Level INTEGER NOT NULL)"""

hasLicense = """
             CREATE TABLE hasLicense (
                  sampleURI VARCHAR(2083) NOT NULL,
                  licenseURI VARCHAR(2083) NOT NULL,
                  FOREIGN KEY (sampleURI)
                      REFERENCES Sample(URI)
                      ON UPDATE CASCADE ON DELETE CASCADE,
                  FOREIGN KEY (licenseURI)
                      REFERENCES License(URI)
                      ON UPDATE CASCADE ON DELETE CASCADE,
                  PRIMARY KEY (sampleURI, licenseURI)
                  )"""

hasLicense2 ="""
             CREATE TABLE hasLicense2 (
                  datasetId INTEGER NOT NULL,
                  licenseURI VARCHAR(2083) NOT NULL,
                  FOREIGN KEY (datasetId)
                          REFERENCES Dataset(id)
                          ON UPDATE CASCADE ON DELETE CASCADE,
                  FOREIGN KEY (licenseURI)
                          REFERENCES License(URI)
                          ON UPDATE CASCADE ON DELETE CASCADE,
                  PRIMARY KEY (datasetId, licenseURI)
                  )"""

workflow = """
           CREATE TABLE Workflow (
                id SERIAL PRIMARY KEY,
                name VARCHAR(255),
                creationTime DATE NOT NULL,
                lastModifTime Date,
                description VARCHAR(255),
                sourceCodeURI VARCHAR(2083),
                programLanguage VARCHAR(255),
                binaryMachineCodeUrl VARCHAR(2083),
                executionEnvironement VARCHAR(255),
                executionDate Date,
                executionOutputLog VARCHAR(255),
                executionErrorLog VARCHAR(255),
                executionComment VARCHAR(255)
                )"""

hasWorkflow = """
              CREATE TABLE hasWorkflow (
                   DatasetId INTEGER NOT NULL,
                   workflowId INTEGER NOT NULL,
                   existingTimes INTEGER NOT NULL,
                   FOREIGN KEY (DatasetId)
                           REFERENCES Dataset(id)
                           ON UPDATE CASCADE ON DELETE CASCADE,
                   FOREIGN KEY (workflowId)
                           REFERENCES Workflow(id)
                           ON UPDATE CASCADE ON DELETE CASCADE,
                   PRIMARY KEY (DatasetId, workflowId, existingTimes))"""

implementation2 = """
                  CREATE TABLE Implementation2 (
                       id SERIAL PRIMARY KEY,
                       name VARCHAR(255),
                       description VARCHAR(255),
                       sourceCodeURL VARCHAR(2083),
                       languageProgram VARCHAR(255))"""

operation = """
            CREATE TABLE Operation (
                 id SERIAL PRIMARY KEY,
                 name VARCHAR(255),
                 description VARCHAR(255))"""

contains = """
           CREATE TABLE contains (
                workflowId INTEGER NOT NULL,
                operationId INTEGER NOT NULL,
                implementationId INTEGER NOT NULL,
                existingTimes INTEGER NOT NULL,
                FOREIGN KEY (workflowId)
                        REFERENCES Workflow (id)
                        ON UPDATE CASCADE ON DELETE CASCADE,
                FOREIGN KEY (operationId)
                        REFERENCES Operation (id)
                        ON UPDATE CASCADE ON DELETE CASCADE,
                FOREIGN KEY (implementationId)
                        REFERENCES Implementation2 (id)
                        ON UPDATE CASCADE ON DELETE CASCADE,
                PRIMARY KEY (workflowId, operationId, implementationId, existingTimes))"""

Tinput = """
         CREATE TABLE Input (
              id SERIAL PRIMARY KEY,
              name VARCHAR(255),
              description VARCHAR(255),
              type VARCHAR(255),
              operationId INTEGER NOT NULL,
              FOREIGN KEY (operationId)
                      REFERENCES Operation(id)
                      ON UPDATE CASCADE ON DELETE CASCADE)"""

output = """
         CREATE TABLE Output (
              id SERIAL PRIMARY KEY,
              name VARCHAR(255),
              description VARCHAR(255),
              constraintc VARCHAR(255),
              operationId INTEGER NOT NULL,
              FOREIGN KEY (operationId)
                      REFERENCES  Operation(id)
                      ON UPDATE CASCADE ON DELETE CASCADE)"""

follows = """
          CREATE TABLE Follows (
               operationId INTEGER NOT NULL,
               followsOperationId INTEGER NOT NULL,
               inputId INTEGER NOT NULL,
               FOREIGN KEY (operationId)
                       REFERENCES  Operation(id)
                       ON UPDATE CASCADE ON DELETE CASCADE,
               FOREIGN KEY (followsOperationId)
                       REFERENCES  Operation(id)
                       ON UPDATE CASCADE ON DELETE CASCADE,
               FOREIGN KEY (inputId)
                       REFERENCES  Output(id)
                       ON UPDATE CASCADE ON DELETE CASCADE,
               PRIMARY KEY (operationId, followsOperationId, inputId))"""

assertion = """
            CREATE TABLE Assertion (
                 id SERIAL PRIMARY KEY,
                 conditionc VARCHAR(255) NOT NULL)"""

correspond2 = """
            CREATE TABLE Correspond2 (
                 inputId INTEGER NOT NULL,
                 assertionId INTEGER NOT NULL,
                 FOREIGN KEY (inputId)
                         REFERENCES  Output(id)
                         ON UPDATE CASCADE ON DELETE CASCADE,
                 FOREIGN KEY (assertionId)
                         REFERENCES  Assertion(id)
                         ON UPDATE CASCADE ON DELETE CASCADE,
                 PRIMARY KEY (inputId, assertionId))"""

toolinstance = """
               CREATE TABLE Tool_instance (
                    id INTEGER PRIMARY KEY)"""

hastoolinstance = """
                  CREATE TABLE hasToolInstance (
                       datasetId INTEGER NOT NULL,
                       toolInstanceId INTEGER NOT NULL,
                       FOREIGN KEY (datasetId)
                               REFERENCES  Dataset(id)
                               ON UPDATE CASCADE ON DELETE CASCADE,
                       FOREIGN KEY (toolInstanceId)
                               REFERENCES  Tool_instance(id)
                               ON UPDATE CASCADE ON DELETE CASCADE,
                       PRIMARY KEY (datasetId, toolInstanceId))"""

datamodel = """
            CREATE TABLE Data_model (
                 id SERIAL PRIMARY KEY,
                 ToolInstanceId INTEGER NOT NULL,
                 FOREIGN KEY (ToolInstanceId)
                         REFERENCES  Tool_instance(id)
                         ON UPDATE CASCADE ON DELETE CASCADE)"""

datamodelobject = """
            CREATE TABLE Data_model_object (
                 id SERIAL PRIMARY KEY,
                 modelId INTEGER NOT NULL,
                 FOREIGN KEY (modelId)
                         REFERENCES  Data_model(id)
                         ON UPDATE CASCADE ON DELETE CASCADE)"""

relatedwork = """
              CREATE TABLE Related_work (
                   id SERIAL PRIMARY KEY,
                   datasetId INTEGER NOT NULL,
                   FOREIGN KEY (datasetId)
                           REFERENCES  Dataset(id)
                           ON UPDATE CASCADE ON DELETE CASCADE)"""

dmp = """
      CREATE TABLE DMP (
           id SERIAL PRIMARY KEY,
           workId INTEGER NOT NULL,
           FOREIGN KEY (workId)
                   REFERENCES  Related_work(id)
                   ON UPDATE CASCADE ON DELETE CASCADE)"""

scientificpaper = """
      CREATE TABLE Scientific_paper (
           id SERIAL PRIMARY KEY,
           workId INTEGER NOT NULL,
           FOREIGN KEY (workId)
                   REFERENCES  Related_work(id)
                   ON UPDATE CASCADE ON DELETE CASCADE)"""

project = """
      CREATE TABLE Project (
           id SERIAL PRIMARY KEY,
           workId INTEGER NOT NULL,
           FOREIGN KEY (workId)
                   REFERENCES  Related_work(id)
                   ON UPDATE CASCADE ON DELETE CASCADE)"""

algorithm = """
      CREATE TABLE Algorithm (
           id SERIAL PRIMARY KEY,
           workId INTEGER NOT NULL,
           FOREIGN KEY (workId)
                   REFERENCES  Related_work(id)
                   ON UPDATE CASCADE ON DELETE CASCADE)"""

attribute = """
            CREATE TABLE Attribute (
                id SERIAL PRIMARY KEY,
                name VARCHAR(255) NOT NULL,
                type VARCHAR(255) NOT NULL,
                missingValuesCount INTEGER,
                entropy float,
                distinctd INTEGER,
                averageClassCount float,
                mostFrequentClassCount INTEGER,
                leastFrquentClassCount INTEGER,
                modeClassCount INTEGER,
                medianClassCount INTEGER,
                nonMissingValuesCount INTEGER,
                normalizedMissingValuesCount INTEGER,
                normalizedPercentageOfMissing INTEGER,
                normalizedPercentageOfNonMissing INTEGER,
                normalizedAveragePercentageOfClass INTEGER,
                normalizedPercentageOfMostFrequentClass INTEGER,
                normalizedPercentageOfLeastFrequentClass INTEGER,
                normalizedModeClassPercentage INTEGER,
                normalizedMedianClassPercentage INTEGER)"""

relationshipatt = """
                  CREATE TABLE RelationshipAtt (
                      id SERIAL PRIMARY KEY,
                      name VARCHAR(255),
                      description VARCHAR(255))"""

analysisattribute = """
                    CREATE TABLE AnalysisAttribute (
                        attributeId INTEGER NOT NULL,
                        attributeId2 INTEGER NOT NULL,
                        valuev float,
                        relationshipId INTEGER NOT NULL,
                        FOREIGN KEY (attributeId)
                                REFERENCES  Attribute(id)
                                ON UPDATE CASCADE ON DELETE CASCADE,
                        FOREIGN KEY (attributeId2)
                                REFERENCES  Attribute(id)
                                ON UPDATE CASCADE ON DELETE CASCADE,
                        FOREIGN KEY (relationshipId)
                                REFERENCES  RelationshipAtt(id)
                                ON UPDATE CASCADE ON DELETE CASCADE,
                        PRIMARY KEY (attributeId, attributeId2))"""

analysistarget = """
                 CREATE TABLE AnalysisTarget (
                      id SERIAL PRIMARY KEY,
                      attributeId INTEGER NOT NULL,
                      FOREIGN KEY (attributeId)
                              REFERENCES  Attribute(id)
                              ON UPDATE CASCADE ON DELETE CASCADE)"""

software = """
           CREATE TABLE Software (
               id SERIAL PRIMARY KEY,
               name VARCHAR(255),
               description VARCHAR(255),
               version VARCHAR(255))"""

algorithm2 = """
             CREATE TABLE Algorithm2 (
                 id SERIAL PRIMARY KEY,
                 name VARCHAR(255),
                 description VARCHAR(255))"""

algosupervised = """
                CREATE TABLE AlgoSupervised (
                algorithmId INTEGER PRIMARY KEY,
                FOREIGN KEY (algorithmId)
                        REFERENCES Algorithm2 (id)
                        ON UPDATE CASCADE ON DELETE CASCADE)"""

algounsupervised = """
                CREATE TABLE AlgounSupervised (
                algorithmId INTEGER PRIMARY KEY,
                FOREIGN KEY (algorithmId)
                        REFERENCES Algorithm2 (id)
                        ON UPDATE CASCADE ON DELETE CASCADE)"""

algoReinforcement = """
                CREATE TABLE AlgoReinforcement (
                algorithmId INTEGER PRIMARY KEY,
                FOREIGN KEY (algorithmId)
                        REFERENCES Algorithm2 (id)
                        ON UPDATE CASCADE ON DELETE CASCADE)"""

deeplearning = """
                CREATE TABLE DeepLearning (
                algorithmId INTEGER PRIMARY KEY,
                FOREIGN KEY (algorithmId)
                        REFERENCES Algorithm2 (id)
                        ON UPDATE CASCADE ON DELETE CASCADE)"""

implementation = """
                 CREATE TABLE Implementation (
                      id SERIAL PRIMARY KEY,
                      name VARCHAR(255),
                      description VARCHAR(255),
                      sourceCodeURL VARCHAR(2038),
                      languageProgram VARCHAR(255),
                      implementsId INTEGER NOT NULL,
                      softwareId INTEGER NOT NULL,
                      algorithmId INTEGER NOT NULL,
                      FOREIGN KEY (softwareId)
                              REFERENCES Software (id)
                              ON UPDATE CASCADE ON DELETE CASCADE,
                      FOREIGN KEY (algorithmId)
                              REFERENCES Algorithm2 (id)
                              ON UPDATE CASCADE ON DELETE CASCADE,
                      FOREIGN KEY (implementsId)
                              REFERENCES Implementation (id)
                              ON UPDATE CASCADE ON DELETE CASCADE
                      )"""

landmarker = """
             CREATE TABLE Landmarker (
                  ImplementationId INTEGER PRIMARY KEY,
                  FOREIGN KEY (implementationId)
                          REFERENCES Implementation (id)
                          ON UPDATE CASCADE ON DELETE CASCADE)"""

parametersetting = """
                   CREATE TABLE ParameterSetting (
                        valuev INTEGER PRIMARY KEY)"""

parameter2 = """
             CREATE TABLE Parameter2 (
                  id SERIAL PRIMARY KEY,
                  name VARCHAR(255))"""

hasparametervalue = """
                    CREATE TABLE hasParameterValue (
                         parameterId INTEGER NOT NULL,
                         valuev INTEGER NOT NULL,
                         FOREIGN KEY (parameterId)
                                 REFERENCES Parameter2 (id)
                                 ON UPDATE CASCADE ON DELETE CASCADE,
                         FOREIGN KEY (valuev)
                                 REFERENCES ParameterSetting (valuev)
                                 ON UPDATE CASCADE ON DELETE CASCADE,
                         PRIMARY KEY (parameterId, valuev))"""

hasparameter = """
               CREATE TABLE hasParameter (
                    implementationId INTEGER NOT NULL,
                    parameterId INTEGER NOT NULL,
                    FOREIGN KEY (implementationId)
                            REFERENCES Implementation (id)
                            ON UPDATE CASCADE ON DELETE CASCADE,
                    FOREIGN KEY (parameterId)
                            REFERENCES Parameter2 (id)
                            ON UPDATE CASCADE ON DELETE CASCADE,
                    PRIMARY KEY (implementationId, parameterId))"""

hasparametersetting = """
                      CREATE TABLE hasParameterSetting (
                           implementationId INTEGER NOT NULL,
                           parameterSettingValue INTEGER NOT NULL,
                           FOREIGN KEY (implementationId)
                                   REFERENCES Implementation (id)
                                   ON UPDATE CASCADE ON DELETE CASCADE,
                           FOREIGN KEY (parameterSettingValue)
                                   REFERENCES ParameterSetting (valuev)
                                   ON UPDATE CASCADE ON DELETE CASCADE,
                           PRIMARY KEY (implementationId, parameterSettingValue))"""

study = """
        CREATE TABLE Study (
             id SERIAL PRIMARY KEY,
             name VARCHAR(255),
             descriptionAnalysis VARCHAR(255),
             studyFromId INTEGER NOT NULL,
             FOREIGN KEY (studyFromId)
                     REFERENCES Study (id)
                     ON UPDATE CASCADE ON DELETE CASCADE
             )"""

analysis = """
           CREATE TABLE Analysis (
               id SERIAL PRIMARY KEY,
               name VARCHAR(255),
               descriptionAnalysis VARCHAR(255),
               typeAnalysis VARCHAR(255),
               subTypeAnalysis VARCHAR(255),
               creationDate Date,
               studyId INTEGER NOT NULL,
               implementationId INTEGER NOT NULL,
               analysisTargetId INTEGER NOT NULL,
               FOREIGN KEY (studyId)
                     REFERENCES Study (id)
                     ON UPDATE CASCADE ON DELETE CASCADE,
               FOREIGN KEY (implementationId)
                     REFERENCES Implementation (id)
                     ON UPDATE CASCADE ON DELETE CASCADE,
               FOREIGN KEY (analysisTargetId)
                     REFERENCES AnalysisTarget (id)
                     ON UPDATE CASCADE ON DELETE CASCADE)"""


cur.execute(user)
cur.execute(groupg)
cur.execute(belongs)
cur.execute(privilege)
cur.execute(hasprivilege)
cur.execute(hasprivilege2)
cur.execute(access)
cur.execute(tag)
cur.execute(source)
cur.execute(sourcefrom)
cur.execute(correspond)
cur.execute(ingest)
cur.execute(sample)
cur.execute(usermetadataString)
cur.execute(usermetadataInteger)
cur.execute(dataset)
cur.execute(includ)
cur.execute(license)
cur.execute(hasLicense)
cur.execute(hasLicense2)
cur.execute(workflow)
cur.execute(hasWorkflow)
cur.execute(implementation2)
cur.execute(operation)
cur.execute(contains)
cur.execute(Tinput)
cur.execute(output)
cur.execute(follows)
cur.execute(assertion)
cur.execute(correspond2)
cur.execute(toolinstance)
cur.execute(hastoolinstance)
cur.execute(datamodel)
cur.execute(datamodelobject)
cur.execute(relatedwork)
cur.execute(dmp)
cur.execute(scientificpaper)
cur.execute(project)
cur.execute(algorithm)
cur.execute(attribute)
cur.execute(relationshipatt)
cur.execute(analysisattribute)
cur.execute(analysistarget)
cur.execute(software)
cur.execute(algorithm2)
cur.execute(algosupervised)
cur.execute(algounsupervised)
cur.execute(algoReinforcement)
cur.execute(deeplearning)
cur.execute(implementation)
cur.execute(landmarker)
cur.execute(parametersetting)
cur.execute(parameter2)
cur.execute(hasparametervalue)
cur.execute(hasparameter)
cur.execute(hasparametersetting)
cur.execute(study)
cur.execute(analysis)
# enregistrer les changements
connection.commit()

# fermer la connection
connection.close()